package es.upm.sistemabienestaremocional.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00687A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFADECFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F26)
val md_theme_light_secondary = Color(0xFFAB3333)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onSecondaryContainer = Color(0xFF410004)
val md_theme_light_tertiary = Color(0xFF835500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB4)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201C00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201C00)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
val md_theme_light_outline = Color(0xFF70797C)
val md_theme_light_inverseOnSurface = Color(0xFFFFF2A7)
val md_theme_light_inverseSurface = Color(0xFF373100)
val md_theme_light_inversePrimary = Color(0xFF56D6F5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00687A)
val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF56D6F5)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_primaryContainer = Color(0xFF004E5D)
val md_theme_dark_onPrimaryContainer = Color(0xFFADECFF)
val md_theme_dark_secondary = Color(0xFFFFB3AE)
val md_theme_dark_onSecondary = Color(0xFF68000C)
val md_theme_dark_secondaryContainer = Color(0xFF8A1B1E)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_tertiary = Color(0xFFFFB954)
val md_theme_dark_onTertiary = Color(0xFF452B00)
val md_theme_dark_tertiaryContainer = Color(0xFF633F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201C00)
val md_theme_dark_onBackground = Color(0xFFF7E467)
val md_theme_dark_surface = Color(0xFF201C00)
val md_theme_dark_onSurface = Color(0xFFF7E467)
val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF201C00)
val md_theme_dark_inverseSurface = Color(0xFFF7E467)
val md_theme_dark_inversePrimary = Color(0xFF00687A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF56D6F5)
val md_theme_dark_outlineVariant = Color(0xFF3F484B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF335C67)

