name: Test App
on:
  push:
    branches:
      - dev
# jobs are run in parallel on different machines
# all steps run in series
jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' #Eclipse
          java-version: '17'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Linters and Test
        run: ./gradlew check
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports
          if: always()