name: Release App
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
# jobs are run in parallel on different machines
# all steps run in series
jobs:
  release:
    name: Release App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' #Eclipse
          java-version: '17'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Linters and Test
        run: ./gradlew check
      - name: Zip Test Results
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r test-reports.zip app/build/reports
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Release AAB
        run: ./gradlew bundleRelease
      - name: Build Release APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          files: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/apk/release/app-release-unsigned.apk
            test-reports.zip